import "./globals.css";

export const metadata = {
  title: "Graduation project",
  description: "Generated by [Musab, Qasim, Hamza, Roghayeh, Sara, Shahd]",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        {children}
      </body>
    </html>
  );
}
