import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import StateProvider from "../stateManagement/StateProvider";
import "./globals.css";

export const metadata = {
  title: "Graduation project",
  description: "Generated by [Musab, Qasim, Hamza, Roghayeh, Sara, Shahd]",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateProvider>
          <div className="flex flex-col justify-between">
          <Header />
            {children}
          <Footer />
          </div>
        </StateProvider>
      </body>
    </html>
  );
}
